from setuptools import setup, find_packages

setup(
    name="folderize",
    description="Folderize is a Python command-line tool that helps you automatically create folder structures based on the layout defined in a `STRUCTURE.md` input file.",
    author="Sanjay RB",
    author_email="sanjaybabu618@gmail.com",
    license="MIT",
    keywords="folderize organize files extensions",
    long_description="""Folderize is a command-line tool that helps you organize your files into folders based on their extensions. Simply run the tool in a directory, and it will create folders for each file type and move the files accordingly.""",
    attrs={
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Utilities",
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Utilities",
    ],
    fullname="folderize",
    platforms="Any",
    requires=["argparse"],
    url="https://github.com/sanjay-rb/folderize",
    version="0.1.0",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    entry_points={
        "console_scripts": [
            "folderize=folderize.core:main",
        ],
    },
)
